display_errors = Off
display_startup_errors = Off
log_errors = On
expose_php = Off
memory_limit = 128M
max_execution_time = 20
post_max_size = 128K
upload_max_filesize = 128K
file_uploads = Off
variables_order = EGPCS
